# Generated by Django 3.1.7 on 2021-03-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210303_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='startDateTime',
            field=models.DateTimeField(),
        ),
    ]
