# Generated by Django 3.1.7 on 2021-03-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210303_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['orderNumber']},
        ),
    ]
