# Generated by Django 3.1.7 on 2021-03-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210303_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaireId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('answers', models.JSONField(max_length=100000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
